from django.db import models

# Create your models here.
class Room(models.Model):
    #id is autogenerated
    #host = 
    #topic =
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)       #false is default; desc is nullable
    #participants =
    updated = models.DateTimeField(auto_now=True)               #snapshot on everytime we save this item
    creted = models.DateTimeField(auto_now_add=True)            #snapshot when created

    def __str__(self):
        return self.name

